### ISSUE TITLE
Support fixture for sky-error-action

### ISSUE THREAD

**Issue by Blackbaud-IsaacAggrey** [blackbaud/skyux-errors#44]
### Expected behavior
```ts
it('should have error action for error fixture', () => {

  const errorFixture = new SkyErrorFixture(fixture, 'permissions-error');
  expect(errorFixture.errorAction).toExist();

});

```

### Actual behavior
There is no fixture method for error action. I'd assume since its template is just `ng-content` then I'd assume the return would be a DebugElement.

[AB#1682081](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1682081)

**Comment by Blackbaud-PaulCrowder** [comment]
Since the button inside the `sky-error-action` element is your own button, you can access it using a selector based on the button's own properties, e.g.

**Comment by Blackbaud-IsaacAggrey** [comment]
Yes, there's an easy workaround and what I'm doing currently, but it's more about a uniform library interface via the fixture from a consumer's POV. Would this be accepted as a contribution?

**Comment by Blackbaud-IsaacAggrey** [comment]
There's also already a pattern of returning the element in cases like this such as in the [`SkyListViewGridFixtureCell`](https://github.com/blackbaud/skyux-list-builder-view-grids/blob/master/src/app/public/testing/list-view-grid-fixture-cell.ts#L13).

**Comment by Blackbaud-PaulCrowder** [comment]
What I stated isn't a workaround but is consistent with how we decide what does and does not need a fixture. If it's an element you own and you can query it without using knowledge of the internal DOM structure of SKY UX components, then we don't provide a fixture. If it's an element you don't own but is rather rendered by a SKY UX component, then we do provide a fixture. An instance of the latter is the close button on the alert component; since the consumer does not own the button, we provide a method for clicking the button via the fixture.

**Comment by Blackbaud-IsaacAggrey** [comment]
Makes sense. I was unaware of the fixture decision process. It was more of a convenience ask...
